---

os:
  - linux
dist: focal

language: python
python:
  - 3.8

services:
  - docker

before_install:
  - sudo apt-get -q update

install:
  - sudo apt-get install -y yamllint
  - sudo pip install ansible
  - sudo pip install ansible-lint
  - ansible-galaxy collection install community.general ansible.netcommon

script:
  - ansible --version
  - ansible-playbook tests/test.yml -i localhost, --syntax-check
  - >
    yamllint .
    && (echo 'YAML lint test: pass' && exit 0)
    || (echo 'YAML lint test: fail' && exit 1)
  - >
    ansible-lint -v tests/test.yml
    && (echo 'Ansible lint test: pass' && exit 0)
    || (echo 'Ansible lint test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
